### ISSUE TITLE
Time steps

### ISSUE THREAD

**Issue by jaseeverett** [patricksykes/ZooMizer#1]
Hi @patricksykes 
When we discussed running ZooMSS in Mizer in Sweden, Gustaf had concerns about our smaller timesteps. My recollection from that discussion was that it was tricky at the time to run Mizer with a shorter timestep. I don't recall if it was because the time-step was hard wired, or if some of the processes represented in Mizer were dependent on a longer time-step. Do you recall this discussion? I just wanted to flag this to check.

**Comment by juliablanchard** [comment]
Hi, I don’t think this should be an issue (and might have been a miscommunication if you discussing processes such as diel vertical  migration, which is not an explicit process here). The time step, and units, in mizer is flexible and default set to a dt of 0.1, and ultimately should be the largest time step that gives a reasonable  approximation ( decrease dt until there isn’t little difference bin equilibrium results). The number of size classes can be increased as well, which might be a good idea when you extend the size range of dynamic consumers.

________________________________

**Comment by ric325** [comment]
﻿Thx Julia

**Comment by patricksykes** [comment]
Closing this now as the different time steps for Mizer fish and ZooMizer zooplankton have now been implemented. This currently lives in the CouplingToMizer branch, but will later be brought into the main branch as things progress.

By way of quick explanation: Mizer models typically run with time step dt=0.1 yr, which is appropriate for fish, while our experience with ZooMSS/ZooMizer is that dt=0.01 yr is far more appropriate for the zooplankton model. There's nothing stopping us from running coupled zooplankton and fish models on the same time step, but it's computationally a bit faster to run the fish model with "slower" time step. This is actually quite easy to do in (Zoo)Mizer via the `steps` parameter in (`new_`)`project_simple()`. In this example, `steps  = fish_dt / zoo_dt`, which is 10, and we set the zooplankton model to run forward 10 steps for every 1 fish step. If we wanted them on the same time scale we'd use `steps = 1` and an appropriate `dt` (e.g. 0.01 yr) for the fish model.

This extends to other processes we might want to model. I think we may indeed have been talking about DVM, and the tricky thing there is that `steps` should be a whole number. So we'd need to be careful about our choice of `dt` if we wanted to extend the approach here to other processes.

**Comment by ric325** [comment]
﻿Well done Patrick and good point about DVM and dt…

From: patricksykes ***@***.***>
Reply to: patricksykes/ZooMizer ***@***.***>
Date: Wednesday, 31 March 2021 at 8:31 pm
To: patricksykes/ZooMizer ***@***.***>
Cc: Anthony Richardson ***@***.***>, Comment ***@***.***>
Subject: Re: [patricksykes/ZooMizer] Time steps (#1)


Closing this now as the different time steps for Mizer fish and ZooMizer zooplankton have now been implemented. This currently lives in the CouplingToMizer branch, but will later be brought into the main branch as things progress.

By way of quick explanation: Mizer models typically run with time step dt=0.1 yr, which is appropriate for fish, while our experience with ZooMSS/ZooMizer is that dt=0.01 yr is far more appropriate for the zooplankton model. There's nothing stopping us from running coupled zooplankton and fish models on the same time step, but it's computationally a bit faster to run the fish model with "slower" time step. This is actually quite easy to do in (Zoo)Mizer via the steps parameter in (new_)project_simple(). In this example, steps = fish_dt / zoo_dt, which is 10, and we set the zooplankton model to run forward 10 steps for every 1 fish step. If we wanted them on the same time scale we'd use steps = 1 and an appropriate dt (e.g. 0.01 yr) for the fish model.

This extends to other processes we might want to model. I think we may indeed have been talking about DVM, and the tricky thing there is that steps should be a whole number. So we'd need to be careful about our choice of dt if we wanted to extend the approach here to other processes.
